# Generated by Django 3.2.9 on 2022-01-05 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_profile_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
    ]
