# Generated by Django 3.2.9 on 2022-01-05 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20220105_2238'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
